// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package image_search

import (
	"r1rpc/api/image_search"
	"r1rpc/internal/service/imagesearch"
)

type ControllerV1 struct {
	service *imagesearch.Service
}

func NewV1() image_search.IImageSearchV1 {
	return NewV1WithService(imagesearch.New())
}

func NewV1WithService(service *imagesearch.Service) image_search.IImageSearchV1 {
	return &ControllerV1{service: service}
}
