// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// channelScanTasksDao is the data access object for the table channel_scan_tasks.
// You can define custom methods on it to extend its functionality as needed.
type channelScanTasksDao struct {
	*internal.ChannelScanTasksDao
}

var (
	// ChannelScanTasks is a globally accessible object for table channel_scan_tasks operations.
	ChannelScanTasks = channelScanTasksDao{internal.NewChannelScanTasksDao()}
)

// Add your custom methods and functionality below.
