// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// dataSourcesDao is the data access object for the table data_sources.
// You can define custom methods on it to extend its functionality as needed.
type dataSourcesDao struct {
	*internal.DataSourcesDao
}

var (
	// DataSources is a globally accessible object for table data_sources operations.
	DataSources = dataSourcesDao{internal.NewDataSourcesDao()}
)

// Add your custom methods and functionality below.
