// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageSearchGroupsDao is the data access object for the table image_search_groups.
// You can define custom methods on it to extend its functionality as needed.
type imageSearchGroupsDao struct {
	*internal.ImageSearchGroupsDao
}

var (
	// ImageSearchGroups is a globally accessible object for table image_search_groups operations.
	ImageSearchGroups = imageSearchGroupsDao{internal.NewImageSearchGroupsDao()}
)

// Add your custom methods and functionality below.
