// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageJobsDao is the data access object for the table image_jobs.
// You can define custom methods on it to extend its functionality as needed.
type imageJobsDao struct {
	*internal.ImageJobsDao
}

var (
	// ImageJobs is a globally accessible object for table image_jobs operations.
	ImageJobs = imageJobsDao{internal.NewImageJobsDao()}
)

// Add your custom methods and functionality below.
