// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageCandidateImagesDao is the data access object for the table image_candidate_images.
// You can define custom methods on it to extend its functionality as needed.
type imageCandidateImagesDao struct {
	*internal.ImageCandidateImagesDao
}

var (
	// ImageCandidateImages is a globally accessible object for table image_candidate_images operations.
	ImageCandidateImages = imageCandidateImagesDao{internal.NewImageCandidateImagesDao()}
)

// Add your custom methods and functionality below.
