// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageCandidatesDao is the data access object for the table image_candidates.
// You can define custom methods on it to extend its functionality as needed.
type imageCandidatesDao struct {
	*internal.ImageCandidatesDao
}

var (
	// ImageCandidates is a globally accessible object for table image_candidates operations.
	ImageCandidates = imageCandidatesDao{internal.NewImageCandidatesDao()}
)

// Add your custom methods and functionality below.
