// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageSearchResponsesDao is the data access object for the table image_search_responses.
// You can define custom methods on it to extend its functionality as needed.
type imageSearchResponsesDao struct {
	*internal.ImageSearchResponsesDao
}

var (
	// ImageSearchResponses is a globally accessible object for table image_search_responses operations.
	ImageSearchResponses = imageSearchResponsesDao{internal.NewImageSearchResponsesDao()}
)

// Add your custom methods and functionality below.
