// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageMatchesDao is the data access object for the table image_matches.
// You can define custom methods on it to extend its functionality as needed.
type imageMatchesDao struct {
	*internal.ImageMatchesDao
}

var (
	// ImageMatches is a globally accessible object for table image_matches operations.
	ImageMatches = imageMatchesDao{internal.NewImageMatchesDao()}
)

// Add your custom methods and functionality below.
