// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageBatchesDao is the data access object for the table image_batches.
// You can define custom methods on it to extend its functionality as needed.
type imageBatchesDao struct {
	*internal.ImageBatchesDao
}

var (
	// ImageBatches is a globally accessible object for table image_batches operations.
	ImageBatches = imageBatchesDao{internal.NewImageBatchesDao()}
)

// Add your custom methods and functionality below.
