// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageSearchItemsDao is the data access object for the table image_search_items.
// You can define custom methods on it to extend its functionality as needed.
type imageSearchItemsDao struct {
	*internal.ImageSearchItemsDao
}

var (
	// ImageSearchItems is a globally accessible object for table image_search_items operations.
	ImageSearchItems = imageSearchItemsDao{internal.NewImageSearchItemsDao()}
)

// Add your custom methods and functionality below.
