// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageAssetsDao is the data access object for the table image_assets.
// You can define custom methods on it to extend its functionality as needed.
type imageAssetsDao struct {
	*internal.ImageAssetsDao
}

var (
	// ImageAssets is a globally accessible object for table image_assets operations.
	ImageAssets = imageAssetsDao{internal.NewImageAssetsDao()}
)

// Add your custom methods and functionality below.
