// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// imageSearchRequestsDao is the data access object for the table image_search_requests.
// You can define custom methods on it to extend its functionality as needed.
type imageSearchRequestsDao struct {
	*internal.ImageSearchRequestsDao
}

var (
	// ImageSearchRequests is a globally accessible object for table image_search_requests operations.
	ImageSearchRequests = imageSearchRequestsDao{internal.NewImageSearchRequestsDao()}
)

// Add your custom methods and functionality below.
