// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// ocrFilterRulesDao is the data access object for the table ocr_filter_rules.
// You can define custom methods on it to extend its functionality as needed.
type ocrFilterRulesDao struct {
	*internal.OcrFilterRulesDao
}

var (
	// OcrFilterRules is a globally accessible object for table ocr_filter_rules operations.
	OcrFilterRules = ocrFilterRulesDao{internal.NewOcrFilterRulesDao()}
)

// Add your custom methods and functionality below.
