// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// searchConfigsDao is the data access object for the table search_configs.
// You can define custom methods on it to extend its functionality as needed.
type searchConfigsDao struct {
	*internal.SearchConfigsDao
}

var (
	// SearchConfigs is a globally accessible object for table search_configs operations.
	SearchConfigs = searchConfigsDao{internal.NewSearchConfigsDao()}
)

// Add your custom methods and functionality below.
