// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// searchTasksDao is the data access object for the table search_tasks.
// You can define custom methods on it to extend its functionality as needed.
type searchTasksDao struct {
	*internal.SearchTasksDao
}

var (
	// SearchTasks is a globally accessible object for table search_tasks operations.
	SearchTasks = searchTasksDao{internal.NewSearchTasksDao()}
)

// Add your custom methods and functionality below.
