// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// searchTaskItemsDao is the data access object for the table search_task_items.
// You can define custom methods on it to extend its functionality as needed.
type searchTaskItemsDao struct {
	*internal.SearchTaskItemsDao
}

var (
	// SearchTaskItems is a globally accessible object for table search_task_items operations.
	SearchTaskItems = searchTaskItemsDao{internal.NewSearchTaskItemsDao()}
)

// Add your custom methods and functionality below.
