// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// sourceChannelsDao is the data access object for the table source_channels.
// You can define custom methods on it to extend its functionality as needed.
type sourceChannelsDao struct {
	*internal.SourceChannelsDao
}

var (
	// SourceChannels is a globally accessible object for table source_channels operations.
	SourceChannels = sourceChannelsDao{internal.NewSourceChannelsDao()}
)

// Add your custom methods and functionality below.
