// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// sourceScanTaskNotesDao is the data access object for the table source_scan_task_notes.
// You can define custom methods on it to extend its functionality as needed.
type sourceScanTaskNotesDao struct {
	*internal.SourceScanTaskNotesDao
}

var (
	// SourceScanTaskNotes is a globally accessible object for table source_scan_task_notes operations.
	SourceScanTaskNotes = sourceScanTaskNotesDao{internal.NewSourceScanTaskNotesDao()}
)

// Add your custom methods and functionality below.
