// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// sourceNoteImagesDao is the data access object for the table source_note_images.
// You can define custom methods on it to extend its functionality as needed.
type sourceNoteImagesDao struct {
	*internal.SourceNoteImagesDao
}

var (
	// SourceNoteImages is a globally accessible object for table source_note_images operations.
	SourceNoteImages = sourceNoteImagesDao{internal.NewSourceNoteImagesDao()}
)

// Add your custom methods and functionality below.
