// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// sourceNotesDao is the data access object for the table source_notes.
// You can define custom methods on it to extend its functionality as needed.
type sourceNotesDao struct {
	*internal.SourceNotesDao
}

var (
	// SourceNotes is a globally accessible object for table source_notes operations.
	SourceNotes = sourceNotesDao{internal.NewSourceNotesDao()}
)

// Add your custom methods and functionality below.
