// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// storageSettingsDao is the data access object for the table storage_settings.
// You can define custom methods on it to extend its functionality as needed.
type storageSettingsDao struct {
	*internal.StorageSettingsDao
}

var (
	// StorageSettings is a globally accessible object for table storage_settings operations.
	StorageSettings = storageSettingsDao{internal.NewStorageSettingsDao()}
)

// Add your custom methods and functionality below.
