// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"r1rpc/internal/dao/internal"
)

// xhsUserProfilesDao is the data access object for the table xhs_user_profiles.
// You can define custom methods on it to extend its functionality as needed.
type xhsUserProfilesDao struct {
	*internal.XhsUserProfilesDao
}

var (
	// XhsUserProfiles is a globally accessible object for table xhs_user_profiles operations.
	XhsUserProfiles = xhsUserProfilesDao{internal.NewXhsUserProfilesDao()}
)

// Add your custom methods and functionality below.
