import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Badge, Button, Card, Flex, Heading, Table, Text } from '@radix-ui/themes'
import { ArrowLeftIcon } from '@radix-ui/react-icons'
import { get } from '../api/client'
import { useFetch } from '../lib/useFetch'
import { statusColor, statusLabel } from '../features/image-search/status'
interface Item{id:string;title:string;externalId:string;status:string;preprocessStatus:string;filterStatus:string;filterReason:string;imageSearchRequestId:string;matched:number;bestScore?:number;errorMessage:string}
interface Task{id:string;title:string;status:string;errorMessage:string}
interface Page{items:Item[];task:Task;total:number;totalPages:number}
export default function SearchTaskDetailPage(){const{id=''}=useParams(),[page,setPage]=useState(1);const data=useFetch(()=>get<Page>(`/api/v1/search-tasks/${encodeURIComponent(id)}/items?page=${page}&pageSize=20`),[id,page]);useEffect(()=>{const timer=window.setInterval(data.reload,5000);return()=>window.clearInterval(timer)},[id,page]);return <Flex direction="column" gap="4"><Flex gap="3" align="center"><Button asChild variant="soft"><Link to="/image-search"><ArrowLeftIcon/>返回搜索任务</Link></Button><div><Flex gap="2" align="center"><Heading size="4">任务资料结果</Heading>{data.data?.task&&<Badge color={statusColor(data.data.task.status)}>{statusLabel(data.data.task.status)}</Badge>}</Flex><Text size="1" color="gray">{id}</Text>{data.data?.task.errorMessage&&<Text as="div" size="2" color="red">{data.data.task.errorMessage}</Text>}</div></Flex><Card><Table.Root><Table.Header><Table.Row><Table.ColumnHeaderCell>资料</Table.ColumnHeaderCell><Table.ColumnHeaderCell>预处理</Table.ColumnHeaderCell><Table.ColumnHeaderCell>过滤</Table.ColumnHeaderCell><Table.ColumnHeaderCell>搜索状态</Table.ColumnHeaderCell><Table.ColumnHeaderCell>匹配</Table.ColumnHeaderCell><Table.ColumnHeaderCell>错误</Table.ColumnHeaderCell><Table.ColumnHeaderCell/></Table.Row></Table.Header><Table.Body>{(data.data?.items??[]).map(i=><Table.Row key={i.id}><Table.RowHeaderCell>{i.title||i.externalId}</Table.RowHeaderCell><Table.Cell>{i.preprocessStatus}</Table.Cell><Table.Cell>{i.filterStatus}{i.filterReason?` · ${i.filterReason}`:''}</Table.Cell><Table.Cell><Badge color={statusColor(i.status)}>{statusLabel(i.status)}</Badge></Table.Cell><Table.Cell>{i.matched?`${(Number(i.bestScore??0)*100).toFixed(1)}%`:'—'}</Table.Cell><Table.Cell>{i.errorMessage||'—'}</Table.Cell><Table.Cell>{i.imageSearchRequestId?<Button asChild size="1" variant="soft"><Link to={`/image-search/results/${i.imageSearchRequestId}`}>查看结果</Link></Button>:'—'}</Table.Cell></Table.Row>)}</Table.Body></Table.Root>{(data.data?.totalPages??0)>1&&<Flex justify="end" gap="3" mt="3"><Button size="1" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Text>第 {page} / {data.data?.totalPages} 页</Text><Button size="1" disabled={page>=(data.data?.totalPages??0)} onClick={()=>setPage(page+1)}>下一页</Button></Flex>}</Card></Flex>}
